close all% Comment this line if you have other figures that you dont want close in Matlab
A = [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0
    0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
    0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0
    0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
    0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
    0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
    0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
    0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
    0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0
    0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
    0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
    0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
    0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    ];

B = [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0
    0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0
    0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0
    0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0
    0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0
    0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0
    0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0
    0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0
    0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0
    0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0
    0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0
    0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0
    0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0
    0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    ];

C = [0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
0	0	0	0	0	0	1	1	1	1	1	1	1	0	0	0	0	0	0	0
0	0	0	0	0	1	1	1	1	1	1	1	1	1	0	0	0	0	0	0
0	0	0	0	1	1	0	0	0	0	0	0	0	1	1	0	0	0	0	0
0	0	0	1	1	0	0	0	0	0	0	0	0	1	1	0	0	0	0	0
0	0	0	1	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
0	0	0	1	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
0	0	0	1	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
0	0	0	1	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
0	0	0	1	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
0	0	0	1	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
0	0	0	1	1	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0
0	0	0	0	1	1	0	0	0	0	0	0	0	1	1	0	0	0	0	0
0	0	0	0	0	1	1	1	1	1	1	1	1	1	0	0	0	0	0	0
0	0	0	0	0	0	1	1	1	1	1	1	1	0	0	0	0	0	0	0
0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
];
%%after loading .mat file generated by python, run this codes below:
figure
imagesc(abs(original), [0 1.1]);
set(gcf,  'Position', [00, 00, 350, 300])
set(gca, 'FontSize', 10)% Font Size
colormap autumn
colorbar
title('Laser Array Intensity Distribution')

phase = HelperClass.quantizePhase(angle(original));
figure
imagesc(phase);
set(gcf,  'Position', [00, 00, 350, 300])
set(gca, 'FontSize', 10)% Font Size
colormap jet
colorbar
title('Laser Array Quantized Phase Distribution')

%% Then copy the quantized near field phase to python or matlab (below) to calculate the far field
nearField = abs(original) .* (exp(1i * phase));
Angular_Spectrum = (fft2(fftshift(original))); %Near Field
figure
imagesc(abs(Angular_Spectrum).^2);
set(gcf,  'Position', [00, 00, 350, 300])
set(gca, 'FontSize', 10)% Font Size
colormap jet
colorbar
title('Recovered Far Field Image')
